doctrine:
    dbal:
        default_connection: mysql
        connections:
            mysql:
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                #server_version: '15'
                url: "%env(resolve:DATABASE_URL)%"
                driver: "pdo_mysql"
#                server_version: "8.0.35"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            oracle:
                schema_filter: ~^.*$~
                driver: "%env(GTWIN_DATABASE_DRIVER)%"
                host: "%env(GTWIN_DATABASE_HOST)%"
                port: "%env(GTWIN_DATABASE_PORT)%"
                dbname: "%env(GTWIN_DATABASE_NAME)%"
                user: "%env(GTWIN_DATABASE_USER)%"
                password: "%env(GTWIN_DATABASE_PASSWORD)%"
                charset: "WE8MSWIN1252"

    orm:
        enable_lazy_ghost_objects: true
        default_entity_manager: default
        controller_resolver:
            auto-mapping: false
        entity_managers:
            default:
                connection: mysql
                auto_mapping: true
                report_fields_where_declared: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity"
                        prefix: 'App\Entity'
            oracle:
                connection: oracle
                report_fields_where_declared: true
                mappings:
                    GTWIN:
                        is_bundle: false
                        type: attribute
                        dir: "%kernel.project_dir%/src/Entity/GTWIN"
                        prefix: 'App\Entity\GTWIN'
                        alias: "GTWIN"

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
