doctrine:
    dbal:
        # configure these for your database server
        default_connection: "mysql"
        connections:
            mysql:
                url: "%env(resolve:DATABASE_URL)%"
                driver: "pdo_mysql"
                server_version: "5.7"
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            oracle:
                driver: "%env(GTWIN_DATABASE_DRIVER)%"
                host: "%env(GTWIN_DATABASE_HOST)%"
                port: "%env(GTWIN_DATABASE_PORT)%"
                dbname: "%env(GTWIN_DATABASE_NAME)%"
                user: "%env(GTWIN_DATABASE_USER)%"
                password: "%env(GTWIN_DATABASE_PASSWORD)%"
                charset: "WE8MSWIN1252"

    orm:
        default_entity_manager: "mysql"
        auto_generate_proxy_classes: true
        entity_managers:
            mysql:
                connection: mysql
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    
                    App:
                        is_bundle: false
                        type: "annotation"
                        dir: "%kernel.project_dir%/src/Entity"
                        prefix: 'App\Entity'
                        alias: "App"
                    MiPagoBundle:
                        type: "annotation"
                        is_bundle: true
                        prefix: 'MiPago\Bundle\Entity'
                        alias: "MiPagoBundle"
            oracle:
                connection: oracle
                mappings:
                    GTWIN:
                        type: "annotation"
                        dir: "%kernel.project_dir%/src/Entity/GTWIN"
                        prefix: 'App\Entity\GTWIN'
                        alias: "GTWIN"
