<?php

namespace App\Repository;

/**
 * ExamRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamInscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
