<?php

namespace App\Repository;

use App\Entity\ReceiptsFile;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ReceiptFileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptsFileRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ReceiptsFile::class);
    }

    public function findAll(): array {
        $qb = $this->createQueryBuilder('r')
            ->leftJoin('r.uploadedBy', 'u')
            ->orderBy('r.receptionDate', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
