<?php

namespace App\Repository;

/**
 * ReceiptFileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptsFileRepository extends \Doctrine\ORM\EntityRepository
{
}
